name: Publish on NPM

on:
  push:
    paths:
      - '**'
    branches:
      - npm-publish

env:
  PUPPETEER_SKIP_DOWNLOAD: true

jobs:
  build_and_test_and_publish:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - name: publish_tokenlist
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
